name: flutter_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
dependency_overrides:
  intl: ^0.18.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  rflutter_alert: ^2.0.4
  get_it: ^7.3.0
  get_it_mixin: ^4.1.1
  jwt_decode: ^0.3.1
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  skeletons: ^0.0.3
  carousel_slider: ^4.1.1
  get: ^4.6.5
  country_code_picker: ^3.0.0
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.4
  # flutter_share: ^2.0.0
  audio_session: ^0.1.25
  share_plus: ^7.2.2
  jiffy: ^6.2.1
  connectivity_plus: ^6.1.4
  flutter_multi_formatter: ^2.5.7
  geocoding: ^2.0.4
  google_nav_bar: ^5.0.6
  indexed: ^0.0.8
  flutter_widget_from_html_core: ^0.16.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.1.2
  loader_overlay: ^2.2.0
  font_awesome_flutter: ^10.5.0
  ionicons: ^0.2.2
  feather_icons: ^1.2.0
  image_cropper: ^9.1.0
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.16.0
  fwfh_webview: ^0.15.4
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.2
  html: ^0.15.4
  flutter_launcher_icons: ^0.13.1
  file_picker: ^10.3.10
  in_app_purchase: ^3.0.7
  rate_limiter: ^1.0.0
  flutter_local_notifications: ^17.2.2
  badges: ^3.0.0
  flutter_vector_icons: ^2.0.0
  easy_localization: ^3.0.3
  social_login_buttons: ^1.0.7
  fwfh_just_audio: ^0.16.0
  screen_protector: ^1.4.12
  google_fonts: ^6.2.1
  syncfusion_flutter_pdfviewer: ^32.2.3

  in_app_purchase_storekit: any
  crop_image: ^1.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.2.0
  build_runner: ^2.3.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/images/icon/
    - assets/images/icon-tab/
  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: semibold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
